package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"
	"time"
)

func TestTTLCache_PositiveAndNegative(t *testing.T) {
	now := time.Unix(0, 0)
	c := newTTLCache()
	c.now = func() time.Time { return now }

	c.set("a", []string{"1.1.1.1"}, 10*time.Second)
	c.set("b", nil, 10*time.Second) // negative entry

	if v, ok := c.get("a"); !ok || len(v) != 1 {
		t.Fatalf("expected positive hit, got %v ok=%v", v, ok)
	}
	if v, ok := c.get("b"); !ok || len(v) != 0 {
		t.Fatalf("expected negative hit, got %v ok=%v", v, ok)
	}
	if _, ok := c.get("missing"); ok {
		t.Fatalf("expected miss for unknown key")
	}
}

func TestTTLCache_Expiry(t *testing.T) {
	now := time.Unix(0, 0)
	c := newTTLCache()
	c.now = func() time.Time { return now }

	c.set("a", []string{"1.1.1.1"}, 10*time.Second)
	now = now.Add(11 * time.Second)
	if _, ok := c.get("a"); ok {
		t.Fatalf("expected entry to be expired")
	}
}
