package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"sync"
	"time"
)

// cacheEntry holds a resolved set of targets and its expiry.
// An empty targets slice represents a cached negative answer.
type cacheEntry struct {
	targets []string
	expires time.Time
}

// ttlCache is a small, concurrency-safe TTL cache keyed by host name. It caches
// both positive (targets present) and negative (empty targets) resolutions so
// repeated queries for the same host do not hit the peers every time.
type ttlCache struct {
	mu    sync.RWMutex
	items map[string]cacheEntry
	now   func() time.Time
}

func newTTLCache() *ttlCache {
	return &ttlCache{
		items: make(map[string]cacheEntry),
		now:   time.Now,
	}
}

// get returns the cached targets and true when a non-expired entry exists.
// A returned (nil/empty, true) means a valid cached negative answer.
func (c *ttlCache) get(host string) ([]string, bool) {
	c.mu.RLock()
	e, ok := c.items[host]
	c.mu.RUnlock()
	if !ok {
		return nil, false
	}
	if c.now().After(e.expires) {
		c.mu.Lock()
		// Only delete if it is still the same expired entry.
		if cur, still := c.items[host]; still && !cur.expires.After(e.expires) {
			delete(c.items, host)
		}
		c.mu.Unlock()
		return nil, false
	}
	return e.targets, true
}

// set stores targets for host with the given TTL.
func (c *ttlCache) set(host string, targets []string, ttl time.Duration) {
	c.mu.Lock()
	c.items[host] = cacheEntry{
		targets: targets,
		expires: c.now().Add(ttl),
	}
	c.mu.Unlock()
}
