package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import "time"

// Opts configures the reactive cross-cluster resolver.
type Opts struct {
	// PeerPort is the port CoreDNS listens on in the peer clusters (the port
	// the localtargets-<host> queries are sent to). Defaults to 53, matching
	// the k8gb edge DNS servers listed in ZoneDelegation.status.dnsServers.
	PeerPort int
	// Timeout bounds a single DNS query to a peer.
	Timeout time.Duration
	// PositiveTTL is how long a successful peer resolution is cached.
	PositiveTTL time.Duration
	// NegativeTTL is how long an all-peers-miss (no targets) is cached.
	NegativeTTL time.Duration
	// SelfGeoTag, when set, excludes the local cluster from the peer list by
	// matching it against the ZoneDelegation DNS server names.
	SelfGeoTag string
	// TTL is the TTL set on the synthesized A records returned to clients.
	TTL uint32
}

const (
	defaultPeerPort    = 53
	defaultTimeout     = 2 * time.Second
	defaultPositiveTTL = 15 * time.Second
	defaultNegativeTTL = 5 * time.Second
	defaultRecordTTL   = uint32(30)
)

// withDefaults returns a copy of the options with unset fields defaulted.
func (o Opts) withDefaults() Opts {
	if o.PeerPort == 0 {
		o.PeerPort = defaultPeerPort
	}
	if o.Timeout == 0 {
		o.Timeout = defaultTimeout
	}
	if o.PositiveTTL == 0 {
		o.PositiveTTL = defaultPositiveTTL
	}
	if o.NegativeTTL == 0 {
		o.NegativeTTL = defaultNegativeTTL
	}
	if o.TTL == 0 {
		o.TTL = defaultRecordTTL
	}
	return o
}
