package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"strings"

	clog "github.com/coredns/coredns/plugin/pkg/log"
	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	"k8s.io/apimachinery/pkg/runtime/schema"
	"k8s.io/client-go/dynamic"
	"k8s.io/client-go/dynamic/dynamicinformer"
	"k8s.io/client-go/tools/cache"
)

var plog = clog.NewWithPlugin("reactive")

// Peer identifies an authoritative CoreDNS server of another cluster serving the
// same delegated zone.
type Peer struct {
	Name string
	IP   string
}

// PeerSource resolves which peer CoreDNS servers are authoritative for a host.
type PeerSource interface {
	// HasSynced reports whether the underlying cache has completed its initial
	// synchronization. Until true, the reactive resolver must fail safe.
	HasSynced() bool
	// PeersForHost returns the peer servers authoritative for host (a fqdn
	// without the trailing dot), excluding the local cluster.
	PeersForHost(host string) []Peer
}

// zoneDelegationGVR is the GroupVersionResource of the k8gb ZoneDelegation CRD.
var zoneDelegationGVR = schema.GroupVersionResource{
	Group:    "k8gb.io",
	Version:  "v1beta1",
	Resource: "zonedelegations",
}

// zoneDelegationSource is a PeerSource backed by a dynamic informer watching the
// cluster-scoped ZoneDelegation resources.
type zoneDelegationSource struct {
	informer   cache.SharedIndexInformer
	selfGeoTag string
}

// NewZoneDelegationSource creates and starts a dynamic informer over the
// ZoneDelegation CRD. selfGeoTag, when non-empty, is used to drop the local
// cluster from the discovered peers.
func NewZoneDelegationSource(ctx context.Context, client dynamic.Interface, selfGeoTag string) PeerSource {
	factory := dynamicinformer.NewDynamicSharedInformerFactory(client, 0)
	informer := factory.ForResource(zoneDelegationGVR).Informer()
	go informer.Run(ctx.Done())
	return &zoneDelegationSource{
		informer:   informer,
		selfGeoTag: selfGeoTag,
	}
}

func (s *zoneDelegationSource) HasSynced() bool {
	return s.informer.HasSynced()
}

func (s *zoneDelegationSource) PeersForHost(host string) []Peer {
	host = strings.ToLower(strings.TrimSuffix(host, "."))
	var peers []Peer
	seen := make(map[string]struct{})
	for _, obj := range s.informer.GetStore().List() {
		u, ok := obj.(*unstructured.Unstructured)
		if !ok {
			continue
		}
		zone, _, _ := unstructured.NestedString(u.Object, "spec", "loadBalancedZone")
		if zone == "" {
			continue
		}
		zone = strings.ToLower(strings.TrimSuffix(zone, "."))
		// host must belong to the delegated zone
		if host != zone && !strings.HasSuffix(host, "."+zone) {
			continue
		}
		servers, _, _ := unstructured.NestedSlice(u.Object, "status", "dnsServers")
		for _, raw := range servers {
			sm, ok := raw.(map[string]interface{})
			if !ok {
				continue
			}
			name, _ := sm["name"].(string)
			address, _ := sm["address"].(string)
			if address == "" {
				continue
			}
			if s.isSelf(name) {
				continue
			}
			if _, dup := seen[address]; dup {
				continue
			}
			seen[address] = struct{}{}
			peers = append(peers, Peer{Name: name, IP: address})
		}
	}
	plog.Infof("resolved %d peer(s) for host %s (store has %d zonedelegation objects)", len(peers), host, len(s.informer.GetStore().List()))
	return peers
}

// isSelf reports whether the given DNS server name belongs to the local cluster,
// based on the configured self geotag. k8gb NS names follow the pattern
// "gslb-ns-<geotag>-<zone>", so the geotag is matched as an exact dash-delimited
// segment rather than a loose substring to avoid false positives.
func (s *zoneDelegationSource) isSelf(name string) bool {
	if s.selfGeoTag == "" {
		return false
	}
	tag := strings.ToLower(s.selfGeoTag)
	for _, seg := range strings.Split(strings.ToLower(name), "-") {
		if seg == tag {
			return true
		}
	}
	return false
}
