package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"testing"

	"github.com/miekg/dns"
)

func TestSetAndDetectReactiveProbe(t *testing.T) {
	m := new(dns.Msg)
	m.SetQuestion("app.example.com.", dns.TypeA)

	if isReactiveProbe(m) {
		t.Fatalf("unmarked query must not be detected as reactive probe")
	}

	setReactiveProbe(m)

	if !isReactiveProbe(m) {
		t.Fatalf("query marked with setReactiveProbe must be detected as reactive probe")
	}

	// Verify standard DNSSEC flags remain untouched
	if m.CheckingDisabled {
		t.Fatalf("CheckingDisabled flag must not be set")
	}
}

func TestProbeSurvivesWirePackUnpack(t *testing.T) {
	m := new(dns.Msg)
	m.SetQuestion("app.example.com.", dns.TypeA)
	setReactiveProbe(m)

	wire, err := m.Pack()
	if err != nil {
		t.Fatalf("failed to pack DNS message: %v", err)
	}

	unpacked := new(dns.Msg)
	if err := unpacked.Unpack(wire); err != nil {
		t.Fatalf("failed to unpack DNS message: %v", err)
	}

	if !isReactiveProbe(unpacked) {
		t.Fatalf("unpacked wire message must still be detected as reactive probe")
	}
}

func TestIsReactiveProbe_IgnoresOtherEDNSOptions(t *testing.T) {
	m := new(dns.Msg)
	m.SetQuestion("app.example.com.", dns.TypeA)

	opt := new(dns.OPT)
	opt.Hdr.Name = "."
	opt.Hdr.Rrtype = dns.TypeOPT
	// Add an unrelated EDNS0 local option
	opt.Option = append(opt.Option, &dns.EDNS0_LOCAL{
		Code: 65002,
		Data: []byte("other-data"),
	})
	m.Extra = append(m.Extra, opt)

	if isReactiveProbe(m) {
		t.Fatalf("different EDNS0 option code must not trigger reactive probe detection")
	}
}
