package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"github.com/miekg/dns"
)

const (
	// EDNS0ReactiveLoopCode is an option code in the RFC 6891 Private / Local Use range (65001-65534 / 0xFDE9-0xFFFE).
	// It marks queries sent between reactive resolvers to prevent cross-cluster loops without touching DNSSEC header flags.
	EDNS0ReactiveLoopCode uint16 = 65001

	// EDNS0ReactiveCookie is the payload carried inside EDNS0ReactiveLoopCode to confirm probe origin.
	EDNS0ReactiveCookie string = "k8gb-reactive"
)

// setReactiveProbe attaches the EDNS0 reactive loop marker to the DNS query.
func setReactiveProbe(m *dns.Msg) {
	opt := m.IsEdns0()
	if opt == nil {
		opt = new(dns.OPT)
		opt.Hdr.Name = "."
		opt.Hdr.Rrtype = dns.TypeOPT
		m.Extra = append(m.Extra, opt)
	}
	opt.Option = append(opt.Option, &dns.EDNS0_LOCAL{
		Code: EDNS0ReactiveLoopCode,
		Data: []byte(EDNS0ReactiveCookie),
	})
}

// isReactiveProbe returns true if the DNS message contains the EDNS0 reactive loop marker.
func isReactiveProbe(r *dns.Msg) bool {
	if r == nil {
		return false
	}
	opt := r.IsEdns0()
	if opt == nil {
		return false
	}
	for _, o := range opt.Option {
		if local, ok := o.(*dns.EDNS0_LOCAL); ok && local.Code == EDNS0ReactiveLoopCode {
			if string(local.Data) == EDNS0ReactiveCookie {
				return true
			}
		}
	}
	return false
}
