package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"net"
	"strconv"

	"github.com/miekg/dns"
)

// Querier resolves the <host> record on a peer CoreDNS server and
// returns the discovered A record IPs (the peer's already-aggregated,
// load-balanced answer).
type Querier interface {
	Query(ctx context.Context, fqdn string, peer Peer) []string
}

// dnsQuerier is the default Querier, sending DNS queries over the network.
type dnsQuerier struct {
	client *dns.Client
	port   int
}

func newDNSQuerier(port int, client *dns.Client) *dnsQuerier {
	return &dnsQuerier{client: client, port: port}
}

func (q *dnsQuerier) Query(ctx context.Context, fqdn string, peer Peer) []string {
	m := new(dns.Msg)
	m.SetQuestion(dns.Fqdn(fqdn), dns.TypeA)
	// Loop guard: mark this as a reactive probe using an EDNS0 private option (RFC 6891).
	// A peer that also misses the host must NOT reactivate it back towards us.
	// We use an EDNS0 option so standard DNSSEC header flags (like CheckingDisabled)
	// remain untouched and retain standard semantics. RecursionDesired is left unset
	// to mirror an authoritative query.
	m.RecursionDesired = false
	setReactiveProbe(m)
	addr := net.JoinHostPort(peer.IP, strconv.Itoa(q.port))
	resp, _, err := q.client.ExchangeContext(ctx, m, addr)
	if err != nil {
		plog.Warningf("failed to query peer %s (%s) for %s: %s", peer.Name, addr, fqdn, err)
		return nil
	}
	var ips []string
	for _, rr := range resp.Answer {
		if a, ok := rr.(*dns.A); ok {
			ips = append(ips, a.A.String())
		}
	}
	return ips
}
