package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"math/rand"
	"net"
	"strings"

	"github.com/coredns/coredns/request"
	"github.com/miekg/dns"
	"golang.org/x/sync/singleflight"
)

// localTargetsPrefix is the label prefix k8gb uses when publishing the
// per-cluster A record for a host. k8gb builds it as fmt.Sprintf("localtargets-%s",
// host) (see controllers/providers/k8gbendpoint/applicationDNSEndpoint.go), so it
// is a single-label DASH prefix (localtargets-<host>), NOT a "localtargets." subdomain.
const localTargetsPrefix = "localtargets-"

// Reactive is a container sub-service that runs after the local gateway lookup.
// When the local lookup produced no record for a host that belongs to a
// delegated zone, it resolves the host live from the authoritative CoreDNS
// servers of the peer clusters (discovered from ZoneDelegation status) by
// querying their <host> records, and answers with the aggregated
// targets. Results are cached with a short TTL and coalesced via singleflight.
type Reactive struct {
	opts    Opts
	peers   PeerSource
	querier Querier
	cache   *ttlCache
	sf      singleflight.Group
}

// NewReactive builds the reactive resolver service.
func NewReactive(opts Opts, peers PeerSource) *Reactive {
	opts = opts.withDefaults()
	client := &dns.Client{Net: "udp", Timeout: opts.Timeout}
	return &Reactive{
		opts:    opts,
		peers:   peers,
		querier: newDNSQuerier(opts.PeerPort, client),
		cache:   newTTLCache(),
	}
}

// Name implements the plugin.Handler interface.
func (s *Reactive) Name() string { return "reactive" }

// ServeDNS implements the plugin.Handler interface. It only acts on local
// misses; on a local hit (answers already present) it is a no-op.
func (s *Reactive) ServeDNS(ctx context.Context, w dns.ResponseWriter, r *dns.Msg) (int, error) {
	state := request.Request{W: w, Req: r}

	// Loop guard: a query carrying CheckingDisabled is a reactive probe sent by
	// a sibling cluster's reactive service (see querier.go). Never reactivate it,
	// otherwise two clusters that both miss the host would query each other
	// forever. This bit is preserved by dns.Msg.SetReply through the pipeline.
	if r.CheckingDisabled {
		return dns.RcodeSuccess, nil
	}

	// A previous service (gateway/wrr) already produced an answer: pass through.
	if len(r.Answer) > 0 {
		return dns.RcodeSuccess, nil
	}
	// Only A queries are resolved via peers (localtargets are A records).
	if state.QType() != dns.TypeA {
		return dns.RcodeSuccess, nil
	}
	host := strings.ToLower(strings.TrimSuffix(state.Name(), "."))
	// Never resolve localtargets-* reactively: peers serve it locally and never
	// re-proxy, which is exactly what guarantees no cross-cluster loop.
	if strings.HasPrefix(host, localTargetsPrefix) {
		return dns.RcodeSuccess, nil
	}

	// Warm-up gate: until the ZoneDelegation cache is synced we cannot know the
	// peers, so fail safe with SERVFAIL. A recursive resolver then retries
	// against a sibling cluster's NS instead of caching a false NXDOMAIN.
	if !s.peers.HasSynced() {
		plog.Infof("miss for %s but ZoneDelegation cache not synced yet, returning SERVFAIL", host)
		return s.writeServfail(w, r)
	}

	peers := s.peers.PeersForHost(host)
	if len(peers) == 0 {
		// Host is not part of any delegated zone we know, or no peers: keep the
		// gateway's negative answer (NXDOMAIN).
		plog.Infof("miss for %s: no peer clusters found for this zone, keeping NXDOMAIN", host)
		return dns.RcodeSuccess, nil
	}
	plog.Infof("miss for %s: querying %d peer(s) for localtargets", host, len(peers))

	targets := s.resolve(ctx, host, peers)
	if len(targets) == 0 {
		// No peer serves this host: it genuinely does not exist. Keep NXDOMAIN.
		plog.Infof("miss for %s: no peer returned targets, keeping NXDOMAIN", host)
		return dns.RcodeSuccess, nil
	}

	m := new(dns.Msg)
	m.SetReply(r)
	m.Authoritative = true
	for _, ip := range targets {
		parsed := net.ParseIP(ip)
		if parsed == nil || parsed.To4() == nil {
			continue
		}
		m.Answer = append(m.Answer, &dns.A{
			Hdr: dns.RR_Header{
				Name:   state.Name(),
				Rrtype: dns.TypeA,
				Class:  dns.ClassINET,
				Ttl:    s.opts.TTL,
			},
			A: parsed,
		})
	}
	if len(m.Answer) == 0 {
		return dns.RcodeSuccess, nil
	}
	if err := w.WriteMsg(m); err != nil {
		plog.Errorf("failed to write reactive response for %s: %s", host, err)
		return dns.RcodeServerFailure, err
	}
	plog.Infof("reactively resolved %s from %d peer target(s)", host, len(m.Answer))
	return dns.RcodeSuccess, nil
}

// resolve returns the targets for host, using the cache and coalescing
// concurrent lookups for the same host with singleflight.
func (s *Reactive) resolve(ctx context.Context, host string, peers []Peer) []string {
	if v, ok := s.cache.get(host); ok {
		return v
	}
	v, _, _ := s.sf.Do(host, func() (interface{}, error) {
		// Another goroutine may have populated the cache while we waited.
		if cached, ok := s.cache.get(host); ok {
			return cached, nil
		}
		targets := s.queryPeers(ctx, host, peers)
		ttl := s.opts.PositiveTTL
		if len(targets) == 0 {
			ttl = s.opts.NegativeTTL
		}
		s.cache.set(host, targets, ttl)
		return targets, nil
	})
	if v == nil {
		return nil
	}
	return v.([]string)
}

// queryPeers asks peers for the full <host> record and returns the first
// non-empty answer. Because every authoritative peer already serves the fully
// aggregated, load-balanced target set for the host, the first peer that has
// the GSLB returns a complete answer — there is no need to fan out to the rest.
// Peers are shuffled so the load is spread across the fleet instead of always
// hitting the same one first, and each peer gets its own bounded timeout.
// A peer that is up but lacks the host answers NXDOMAIN in ~1 RTT (cheap), so
// traversing misses is fast; only genuinely down peers cost the full timeout.
func (s *Reactive) queryPeers(ctx context.Context, host string, peers []Peer) []string {
	shuffled := make([]Peer, len(peers))
	copy(shuffled, peers)
	rand.Shuffle(len(shuffled), func(i, j int) {
		shuffled[i], shuffled[j] = shuffled[j], shuffled[i]
	})

	for _, p := range shuffled {
		queryCtx, cancel := context.WithTimeout(ctx, s.opts.Timeout)
		ips := s.querier.Query(queryCtx, host, p)
		cancel()
		if len(ips) == 0 {
			continue
		}
		// Early return: dedup within this peer's answer and stop.
		seen := make(map[string]struct{}, len(ips))
		out := make([]string, 0, len(ips))
		for _, ip := range ips {
			if _, dup := seen[ip]; dup {
				continue
			}
			seen[ip] = struct{}{}
			out = append(out, ip)
		}
		plog.Infof("reactively resolved %s from peer %s (%s)", host, p.Name, p.IP)
		return out
	}
	return nil
}

// writeServfail replaces the current response with SERVFAIL.
func (s *Reactive) writeServfail(w dns.ResponseWriter, r *dns.Msg) (int, error) {
	m := new(dns.Msg)
	m.SetRcode(r, dns.RcodeServerFailure)
	if err := w.WriteMsg(m); err != nil {
		return dns.RcodeServerFailure, err
	}
	return dns.RcodeSuccess, nil
}
