package reactive

/*
Copyright 2022 The k8gb Contributors

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

Generated by GoLic, for more details see: https://github.com/AbsaOSS/golic
*/

import (
	"context"
	"sync/atomic"
	"testing"

	"github.com/coredns/coredns/plugin/pkg/dnstest"
	"github.com/coredns/coredns/plugin/test"
	"github.com/miekg/dns"
)

// fakePeerSource is an injectable PeerSource for tests.
type fakePeerSource struct {
	synced bool
	peers  map[string][]Peer
}

func (f *fakePeerSource) HasSynced() bool { return f.synced }

func (f *fakePeerSource) PeersForHost(host string) []Peer { return f.peers[host] }

// fakeQuerier is an injectable Querier for tests. It records the fqdns queried.
type fakeQuerier struct {
	results map[string][]string // key: "fqdn|peerIP" -> ips
	calls   int32
}

func (f *fakeQuerier) Query(_ context.Context, fqdn string, peer Peer) []string {
	atomic.AddInt32(&f.calls, 1)
	return f.results[fqdn+"|"+peer.IP]
}

func newTestReactive(peers PeerSource, q Querier) *Reactive {
	s := NewReactive(Opts{}, peers)
	s.querier = q
	return s
}

func query(host string, qtype uint16) *dns.Msg {
	m := new(dns.Msg)
	m.SetQuestion(dns.Fqdn(host), qtype)
	return m
}

func TestServeDNS_Passthrough_WhenAnswerPresent(t *testing.T) {
	q := &fakeQuerier{}
	s := newTestReactive(&fakePeerSource{synced: true}, q)

	r := query("app.corpplatform.intranet", dns.TypeA)
	r.Answer = append(r.Answer, test.A("app.corpplatform.intranet. 30 IN A 1.2.3.4"))
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, err := s.ServeDNS(context.Background(), rec, r)
	if err != nil || code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d err=%v", code, err)
	}
	if atomic.LoadInt32(&q.calls) != 0 {
		t.Fatalf("querier should not be called on passthrough, got %d calls", q.calls)
	}
	if rec.Msg != nil {
		t.Fatalf("reactive must not write when an answer is already present")
	}
}

func TestServeDNS_Servfail_WhenNotSynced(t *testing.T) {
	s := newTestReactive(&fakePeerSource{synced: false}, &fakeQuerier{})
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, err := s.ServeDNS(context.Background(), rec, query("app.corpplatform.intranet", dns.TypeA))
	if err != nil || code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d err=%v", code, err)
	}
	if rec.Msg == nil || rec.Msg.Rcode != dns.RcodeServerFailure {
		t.Fatalf("expected SERVFAIL during warm-up, got %+v", rec.Msg)
	}
}

func TestServeDNS_ResolvesFromPeers(t *testing.T) {
	host := "app.corpplatform.intranet"
	peers := &fakePeerSource{
		synced: true,
		peers:  map[string][]Peer{host: {{Name: "eu", IP: "10.0.0.1"}, {Name: "us", IP: "10.0.0.2"}}},
	}
	// Every authoritative peer serves the same fully-aggregated target set, so
	// the first non-empty answer is complete. Both peers return the same set.
	q := &fakeQuerier{results: map[string][]string{
		host + "|10.0.0.1": {"192.168.1.10", "192.168.1.11"},
		host + "|10.0.0.2": {"192.168.1.10", "192.168.1.11"},
	}}
	s := newTestReactive(peers, q)
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, err := s.ServeDNS(context.Background(), rec, query(host, dns.TypeA))
	if err != nil || code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d err=%v", code, err)
	}
	if rec.Msg == nil || rec.Msg.Rcode != dns.RcodeSuccess {
		t.Fatalf("expected success answer, got %+v", rec.Msg)
	}
	if len(rec.Msg.Answer) != 2 {
		t.Fatalf("expected 2 A records, got %d: %+v", len(rec.Msg.Answer), rec.Msg.Answer)
	}
	// Early return: only the first (shuffled) peer that answers is queried.
	if got := atomic.LoadInt32(&q.calls); got != 1 {
		t.Fatalf("expected early return after 1 peer query, got %d", got)
	}
}

func TestServeDNS_EarlyReturn_SkipsDownPeer(t *testing.T) {
	host := "app.corpplatform.intranet"
	peers := &fakePeerSource{
		synced: true,
		peers:  map[string][]Peer{host: {{Name: "eu", IP: "10.0.0.1"}, {Name: "us", IP: "10.0.0.2"}}},
	}
	// Only one peer has the host; the other returns empty (miss/down). Regardless
	// of shuffle order, we must still resolve by falling through to the peer that
	// answers, and never call more than the two peers.
	q := &fakeQuerier{results: map[string][]string{host + "|10.0.0.2": {"192.168.1.10"}}}
	s := newTestReactive(peers, q)
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, _ := s.ServeDNS(context.Background(), rec, query(host, dns.TypeA))
	if code != dns.RcodeSuccess || rec.Msg == nil || len(rec.Msg.Answer) != 1 {
		t.Fatalf("expected 1 A record resolved via the answering peer, got code=%d msg=%+v", code, rec.Msg)
	}
	if got := atomic.LoadInt32(&q.calls); got < 1 || got > 2 {
		t.Fatalf("expected between 1 and 2 peer queries, got %d", got)
	}
}

func TestServeDNS_KeepsNXDOMAIN_WhenNoPeers(t *testing.T) {
	s := newTestReactive(&fakePeerSource{synced: true, peers: map[string][]Peer{}}, &fakeQuerier{})
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, err := s.ServeDNS(context.Background(), rec, query("nope.corpplatform.intranet", dns.TypeA))
	if err != nil || code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d err=%v", code, err)
	}
	if rec.Msg != nil {
		t.Fatalf("reactive must leave the gateway's NXDOMAIN untouched, wrote %+v", rec.Msg)
	}
}

func TestServeDNS_KeepsNXDOMAIN_WhenPeersHaveNoTargets(t *testing.T) {
	host := "app.corpplatform.intranet"
	peers := &fakePeerSource{synced: true, peers: map[string][]Peer{host: {{Name: "eu", IP: "10.0.0.1"}}}}
	s := newTestReactive(peers, &fakeQuerier{results: map[string][]string{}})
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, _ := s.ServeDNS(context.Background(), rec, query(host, dns.TypeA))
	if code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d", code)
	}
	if rec.Msg != nil {
		t.Fatalf("expected NXDOMAIN kept, wrote %+v", rec.Msg)
	}
}

func TestServeDNS_SkipsLocalTargets_NoLoop(t *testing.T) {
	q := &fakeQuerier{}
	s := newTestReactive(&fakePeerSource{synced: true}, q)
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, _ := s.ServeDNS(context.Background(), rec, query("localtargets-app.corpplatform.intranet", dns.TypeA))
	if code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d", code)
	}
	if atomic.LoadInt32(&q.calls) != 0 {
		t.Fatalf("localtargets-* must never trigger a peer query")
	}
	if rec.Msg != nil {
		t.Fatalf("localtargets-* must pass through untouched")
	}
}

func TestServeDNS_SkipsNonA(t *testing.T) {
	q := &fakeQuerier{}
	s := newTestReactive(&fakePeerSource{synced: true}, q)
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	code, _ := s.ServeDNS(context.Background(), rec, query("app.corpplatform.intranet", dns.TypeAAAA))
	if code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d", code)
	}
	if atomic.LoadInt32(&q.calls) != 0 {
		t.Fatalf("non-A queries must not trigger a peer query")
	}
}

func TestServeDNS_SkipsReactiveProbe_CD_NoLoop(t *testing.T) {
	host := "app.corpplatform.intranet"
	peers := &fakePeerSource{synced: true, peers: map[string][]Peer{host: {{Name: "eu", IP: "10.0.0.1"}}}}
	q := &fakeQuerier{results: map[string][]string{host + "|10.0.0.1": {"192.168.1.10"}}}
	s := newTestReactive(peers, q)
	rec := dnstest.NewRecorder(&test.ResponseWriter{})

	r := query(host, dns.TypeA)
	r.CheckingDisabled = true // simulate an incoming reactive probe from a sibling cluster
	code, _ := s.ServeDNS(context.Background(), rec, r)
	if code != dns.RcodeSuccess {
		t.Fatalf("unexpected code=%d", code)
	}
	if atomic.LoadInt32(&q.calls) != 0 {
		t.Fatalf("a CD-marked probe must never trigger a peer query (loop guard)")
	}
	if rec.Msg != nil {
		t.Fatalf("a CD-marked probe must pass through untouched")
	}
}

func TestServeDNS_CacheAvoidsSecondQuery(t *testing.T) {
	host := "app.corpplatform.intranet"
	peers := &fakePeerSource{synced: true, peers: map[string][]Peer{host: {{Name: "eu", IP: "10.0.0.1"}}}}
	q := &fakeQuerier{results: map[string][]string{host + "|10.0.0.1": {"192.168.1.10"}}}
	s := newTestReactive(peers, q)

	for i := 0; i < 3; i++ {
		rec := dnstest.NewRecorder(&test.ResponseWriter{})
		if _, err := s.ServeDNS(context.Background(), rec, query(host, dns.TypeA)); err != nil {
			t.Fatalf("unexpected err: %v", err)
		}
	}
	if got := atomic.LoadInt32(&q.calls); got != 1 {
		t.Fatalf("expected 1 peer query due to cache, got %d", got)
	}
}
